### ISSUE TITLE
Remove leading newline in generated .gitignore file

### ISSUE THREAD

**Issue by mfonism** [mfonism/django-classy-start#1]
Currently, the generated `.gitignore` file has a leading newline character which causes my poor AR eyes to bleed.

![classy-start-gitignore](https://user-images.githubusercontent.com/50708034/95098933-36d54e80-0727-11eb-920a-6af1e67a8f20.png)

It will be more aesthetically pleasing if this rogue newline at the start of the file were taken out.

The template file can be found at https://github.com/mfonism/django-classy-start/blob/main/classy_start/conf/project_template/gitignore.py-tpl

**Comment by avallbona** [comment]
Hi @mfonism I can work on this.
