### ISSUE TITLE
Remove trailing newline in generated views.py file (for apps)

### ISSUE THREAD

**Issue by mfonism** [mfonism/django-classy-start#2]
Currently, the `views.py` file generated by `classy-start app <app-name>` has a trailing newline character (or a leading newline character, depending on how you want to see it), and this causes my poor linter to complain.

![classy-start-views](https://user-images.githubusercontent.com/50708034/95100172-b9aad900-0728-11eb-86e4-97be86fb4a66.png)

It would be more aesthetically pleasing if this rogue newline were taken out.

The template file can be found at https://github.com/mfonism/django-classy-start/blob/main/classy_start/conf/app_template/views.py-tpl

**Comment by avallbona** [comment]
I can work on this @mfonism

**Comment by mfonism** [comment]
Feel free to work on it @avallbona

**Comment by avallbona** [comment]
May you label your repo with the hacktoberfest label?
